### ISSUE TITLE
Hot reload not working! 

### ISSUE THREAD

**Issue by LinArcX** [hankchiutw/flutter-reload.vim#1]
Hi. i try your plugin. so open a new terminal, run:
`flutter run`
It's output:
```
Launching lib/main.dart on HUAWEI RIO L01 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.7s
Gradle task 'assembleDebug'...                                   
Gradle task 'assembleDebug'... Done                          8.0s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                     ⣻^C
```
And in another terminal open the neovim and edit the source code. but hot reload not working.

**Comment by mauritsvdvijgh** [comment]
On macos the command `pgrep -f flutter_tool`in:
```
!kill -SIGUSR1 "$(pgrep -f flutter_tool)" &> /dev/null
```
which is the command the plugin executes when you save a .dart file.

Returns 2 different PIDs:

```
pgrep -f flutter_tools
67437
97624
```

meaning that the kill command does this:

```
kill -SIGUSR1 "$(pgrep -f flutter_tool)"
kill: illegal pid: 67437\n97624
```

I fixed this by changing the command to:

```
function! reload#TriggerHotReload() abort
	silent execute '!kill -SIGUSR1 "$(pgrep -f flutter_tools.snapshot)" &> /dev/null'
endfunction
```

I forked this and applied this as a hotfix for myself here: https://github.com/mauritsvdvijgh/flutter-reload.vim

**Comment by hankchiutw** [comment]
Yes, fixed here https://github.com/hankchiutw/flutter-reload.vim/commit/e6b441698c61171526514e2f89927bb9225611d2
