### ISSUE TITLE
when file saved, flutter is not reloading

### ISSUE THREAD

**Issue by yshuman1** [hankchiutw/flutter-reload.vim#2]
hi, 
i'm trying your plugin out and it doesnt seem to be working. 
Here is what I'm using:
MacOS
vim
tmux

I have a pane open running vim and I edit main.dart in my lib folder of a project.
in another tmux pane i have flutter running on an emulator
when i save a change to main.dart hot reload doesnt occur automatically. 

What information could I give you to help debug?

**Comment by hankchiutw** [comment]
Do you have any output by executing `pgrep -f flutter_tool.snapshot`?

**Comment by yshuman1** [comment]
nothing

**Comment by hankchiutw** [comment]
Should be fixed in 930a8bff082f06699561de50185bfe88bf9a7d9d, please upgrade and try!

**Comment by yshuman1** [comment]
it worked! thx!
